Update README.md
Seagate/cortx-hare pull request #1345
Opened 2020-09-28 10:54 UTC by pujamudaliar

Codacy badge link added in README.md file , which shows codacy code quality status and redirects to the codacy repository page.

2020-09-29 11:09 UTC, mukul-seagate11 approved these changes
looks good

2020-09-29 20:10 UTC, vvv commented
> Update README.md

@pujamudaliar The patch does not conform to Hare's [patch requirements](https://github.com/Seagate/cortx-hare/blob/dev/rfc/9/README.md#22-patch-requirements).

> 2. A patch SHOULD be a minimal and accurate answer to exactly one identified and agreed problem.
>
> \[...\]
>
> 6. A patch commit message SHOULD consist of a single short (less than 50 characters) line stating the problem ("Problem: ...") being solved, followed by a blank line and then the proposed solution ("Solution: ...").

What problem is being solved?

cc @Saumya-Sunder

2020-09-29 20:10 UTC, vvv requested changes
> Update README.md

@pujamudaliar The patch does not conform to Hare's [patch requirements](https://github.com/Seagate/cortx-hare/blob/dev/rfc/9/README.md#22-patch-requirements).

> 2. A patch SHOULD be a minimal and accurate answer to exactly one identified and agreed problem.
>
> \[...\]
>
> 6. A patch commit message SHOULD consist of a single short (less than 50 characters) line stating the problem ("Problem: ...") being solved, followed by a blank line and then the proposed solution ("Solution: ...").

What problem is being solved?

cc @Saumya-Sunder

2020-09-30 03:37 UTC, mukul-seagate11 commented
@NeeravChoudhari, Can you please take this forward as we had already made a practice to add Codacy badges for all the repos as,

![image](https://user-images.githubusercontent.com/65269273/94640442-6128a580-02fc-11eb-93ef-277be34065a6.png)

2020-09-30 06:12 UTC, pujamudaliar commented
Problem: Codacy Badge needs to be included in README.md file , which provides code quality status for every commit in the repository.It also contains link to the repository in Codacy.
Solution: Codacy badge link is copied from the settings tab under Codacy Hare repository and pasted in README.md file.

2020-09-30 06:19 UTC, pujamudaliar commented on README.md
> +[![Codacy Badge](https://app.codacy.com/project/badge/Grade/0642a6f7d92542e39f2dd68139cd5586)](https://www.codacy.com/gh/Seagate/cortx-hare/dashboard?utm_source=github.com&amp;utm_medium=referral&amp
Problem: Codacy Badge needs to be included in README.md file , which provides code quality status for every commit in the repository.It also contains link to the repository in Codacy.
Solution: Codacy badge link is copied from the settings tab under Codacy Hare repository and pasted in README.md file.

2020-09-30 14:31 UTC, vvv commented
> @NeeravChoudhari, Can you please take this forward as we had already made a practice to add Codacy badges for all the repos as I dont understand why the concern is raised for Hare

@mukul-seagate11 I speak some English, you can contact me as well. 🙂

2020-09-30 14:38 UTC, vvv approved these changes

2020-09-30 15:12 UTC, merged