Added Support.md
Seagate/cortx-hare pull request #1412
Opened 2020-12-01 14:22 UTC by Saumya-Sunder

Added Support.md

Signed-off-by: Saumya Sunder <saumya.sunder@seagate.com>

2021-02-11 09:42 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-02-11 11:09 UTC, knekrasov requested changes
I doubt that we have to add a document with broken links. Probably the text or links must be updated.

2021-02-11 11:09 UTC, knekrasov commented on SUPPORT.md
> +-   Attend our [Monthly Meet an Architect](doc/meetings/README.rst) meetings to learn about CORTX architecture and participate in a Question and Answer Session.
The link is not working (404 is shown)

2021-02-11 11:09 UTC, knekrasov commented on SUPPORT.md
> +-   Ask and answer questions in our [Frequently Asked Questions](FAQs.md) page.
The link is not working (404 is shown)

2021-02-11 11:09 UTC, knekrasov commented on SUPPORT.md
> +-   Learn how to integrate CORTX with other technologies [here](doc/integrations/README.rst).
The link is not working (404 is shown)

2021-02-12 22:27 UTC, Saumya-Sunder commented on SUPPORT.md
> +-   Attend our [Monthly Meet an Architect](doc/meetings/README.rst) meetings to learn about CORTX architecture and participate in a Question and Answer Session.
Fixed the link

2021-02-12 22:27 UTC, Saumya-Sunder commented on SUPPORT.md
> +-   Ask and answer questions in our [Frequently Asked Questions](FAQs.md) page.
Fixed the link

2021-02-12 22:27 UTC, Saumya-Sunder commented on SUPPORT.md
> +-   Learn how to integrate CORTX with other technologies [here](doc/integrations/README.rst).
Fixed the link

2021-02-20 09:38 UTC, knekrasov approved these changes

2021-04-15 02:23 UTC, mssawant approved these changes

2021-04-15 02:23 UTC, merged