CORTX-19185: PEP 257 tool Codacy issues
Seagate/cortx-hare pull request #2120
Opened 2022-06-17 11:24 UTC by hessio

Solution: Follow docstring conventions as outlined in
tool: https://peps.python.org/pep-0257/

Signed-off-by: hessio <patrick.hession@seagate.com>

2022-06-17 11:27 UTC, d-nayak requested changes

2022-06-17 11:27 UTC, d-nayak commented on hax/hax/motr/planner.py
> +        ''' mthod invoked by the worker thread when the command is executed.
"Method" ... ?

2022-06-21 08:00 UTC, vaibhavparatwar approved these changes

2022-06-21 08:24 UTC, Shreya-18 commented
@hessio I can still new 14 codacy issues added

https://app.codacy.com/gh/Seagate/cortx-hare/pullRequest?prid=9634694&bid=29705438

Are we not supposed to address them?

2022-06-22 07:44 UTC, vaibhavparatwar commented
retest this please

2022-06-23 05:42 UTC, Shreya-18 commented on hax/hax/consul/cache.py
> +    create the instance of cache that nested functions can pick up.
create -> Create

2022-06-23 05:44 UTC, Shreya-18 commented on hax/hax/motr/planner.py
> +        returns True group_id equal to the currently active group
returns -> Returns

2022-06-23 05:45 UTC, Shreya-18 commented on hax/hax/motr/planner.py
> +        '''method invoked by the worker thread when the command is executed.
method -> Method

2022-06-23 05:47 UTC, Shreya-18 commented on provisioning/miniprov/hare_mp/cdf.py
> +        get motr client nodes.
get-> Get

2022-06-23 05:48 UTC, Shreya-18 requested changes
Please look at the minor changes. Also squash all the commits.

2022-06-23 11:49 UTC, Shreya-18 commented
@hessio Looks like 7 new codacy issues are added. :(
https://app.codacy.com/gh/Seagate/cortx-hare/pullRequest?prid=9634694&bid=29705438

Please have a look!

2022-06-23 22:16 UTC, mssawant approved these changes

2022-06-27 12:57 UTC, Shreya-18 approved these changes

2022-06-27 12:58 UTC, Shreya-18 approved these changes

2022-06-27 13:12 UTC, d-nayak approved these changes

2022-06-27 13:16 UTC, merged